### ISSUE TITLE
Ready by July 16?

### ISSUE THREAD

**Issue by lwaldron** [hukai916/IntegratedChIPseqWorkshop#1]
I just wanted to make sure you'll have things up and running by July 16? Please reach out on the #biocworkshopbook channel (or to me!) if you need help. On the 17th we'll have to prune workshops that are not building properly from the program, which we really don't want to do!

**Comment by hukai916** [comment]
Hi Levi,

Thanks very much for reaching out!

I am at the final stage of testing out the docker image, I believe I can
nail it by 16th.

Have a good week!

--Kai

**Comment by mdozmorov** [comment]
As a follow-up, here are the [instructions](https://github.com/seandavi/BuildABiocWorkshop2020/blob/master/vignettes/HOWTO_BUILD_WORKSHOP.Rmd).

**Comment by hukai916** [comment]
Thank you very much Mikhail,

I do have a quick question if you don't mind.

I am not very familiar with GitHub Actions. I assume that when I git push
the repo to GitHub, the basic_checks.yaml would trigger the actions that
would build/push docker image and build the pkgdown site. I notice that I
must git push under Ubuntu environment, right? I am working with my Mac,
Git push would trigger the Actions seems to me.

Thanks again for the instructions.

**Comment by mdozmorov** [comment]
That is correct, the `basic_checks.yaml` will initiate GH-actions. Your workshop is fairly uncomplicated in terms of dependencies, so everything should work at the first try. Just make sure everything is done exactly as in the instructions, including using lowercase for Docker repository. Please, ask more, and join [#biocworkshopbook](https://community-bioc.slack.com/archives/CJDMYKG2U) for community help.

**Comment by hukai916** [comment]
Thank you very much for your prompt reply Mikhail,

I am working on my Mac, and git push would NOT trigger anything except
pushing the repo to GitHub. Seems to me that the GitHub Actions are not
triggered when runing on a Mac. I am now testing with a Ubuntu machine.
Please let me know if I am not on the right track.

Thanks,

**Comment by hukai916** [comment]
BTW, can you provide more details on how to join the slacker channel? It
keeps popping that my email is not correct.

--Kai

**Comment by lwaldron** [comment]
Kai, you can sign up for Slack at https://bioc-community.herokuapp.com/

**Comment by mdozmorov** [comment]
Specifically, join the [#biocworkshopbook](https://community-bioc.slack.com/archives/CJDMYKG2U) channel. 

As for Mac or any other OS - it shouldn't matter as long you follow the instructions.

**Comment by hukai916** [comment]
I now have the docker image and pkgdown site ready. Please close the issue or let me know if you found other problems, thanks!

**Comment by mdozmorov** [comment]
All components seem to work. @lwaldron, please, close.

**Comment by hukai916** [comment]
Thank you both!
